### ISSUE TITLE
Dates not seen

### ISSUE THREAD

**Issue by Jaideep25** [rawfour/weather-app-react#3]
Hi! Your app is amazing no doubt, just their is 1 problem, could you please add dates for the forcasts? It becomes confusing like this.. 
![image](https://user-images.githubusercontent.com/67269475/116095455-0dc9da80-a6c6-11eb-99c9-36d64a2377e0.png)

**Comment by ItsLeon15** [comment]
Could you explain on what you mean by that? Like add 26th April instead of 04.26??

**Comment by Jaideep25** [comment]
Yep!

**Comment by ItsLeon15** [comment]
I mean, I still need to get the app to work but after that I can always
change it for you!

**Comment by ItsLeon15** [comment]
I'll fix it in the morning, just by any chance did you manage to get past the eslint error?

**Comment by Jaideep25** [comment]
Yup, I hope this helps! 
https://stackoverflow.com/questions/67399785/how-to-solve-npm-install-error-npm-err-code-1

**Comment by ItsLeon15** [comment]
That's with Python?

**Comment by Jaideep25** [comment]
Yes... That's the problem.... If you look closely it asks you for py too...

**Comment by ItsLeon15** [comment]
Ah okay, makes sense then. I'll get it running and sort out the code tomorrow. Shouldn't take that long.

**Comment by Jaideep25** [comment]
Hey @ItsLeon15 , delete package-lock.json too ;) Then try, cause it just worked for me! I'm sharing the logs!

```PS D:\Jaideep25\Downloads\weather-app-react-master\weather-app-react-master> npm install
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.      
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated eslint-loader@3.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated @types/testing-library__dom@7.5.0: This is a stub types definition. testing-library__dom provides its own type definitions, so you do not need this installed.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated html-webpack-plugin@4.0.0-beta.5: please switch to a stable version
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 2279 packages, and audited 2280 packages in 4m

113 packages are looking for funding
  run `npm fund` for details

38 vulnerabilities (2 low, 9 moderate, 27 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.```

**Comment by ItsLeon15** [comment]
Ah perfect, I'll downgrade Python to 2.7 and remove package-lock.json and try again. Thanks for your help. I'll fork the project and update it so you can see the changes

**Comment by Jaideep25** [comment]
Sure!

**Comment by ItsLeon15** [comment]
What about this error?

`$ npm start

> weather-app@0.1.0 start C:\Users\Build 45\Downloads\1\1
> react-scripts start

i ｢wds｣: Project is running at http://192.168.56.1/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\Build 45\Downloads\1\1\public
i ｢wds｣: 404s will fallback to /index.html
Starting the development server...

events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/s', '/c', 'start', '""', '/b', '"http://localhost:3000/"' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weather-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weather-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Build 45\AppData\Roaming\npm-cache\_logs\2021-06-29T11_41_05_421Z-debug.log

`

**Comment by ItsLeon15** [comment]
```
./src/index.sass (C:/Users/Build 45/AppData/Roaming/npm/node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!C:/Users/Build 45/AppData/Roaming/npm/node_modules/react-scripts/node_modules/postcss-loader/src??postcss!C:/Users/Build 45/AppData/Roaming/npm/node_modules/react-scripts/node_modules/resolve-url-loader??ref--5-oneOf-6-3!C:/Users/Build 45/AppData/Roaming/npm/node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/index.sass)
Cannot find module 'sass'
Require stack:
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\sass-loader\dist\utils.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\sass-loader\dist\index.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\sass-loader\dist\cjs.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\webpack\lib\NormalModule.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\webpack\lib\Compiler.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\node_modules\webpack\lib\webpack.js
- C:\Users\Build 45\AppData\Roaming\npm\node_modules\react-scripts\scripts\start.js
```

I've done npm install sass but it doesn't work

**Comment by Jaideep25** [comment]
mm Sec.... I updated package.json lemme send the copy...

```
{
  "homepage": "https://rawfour.github.io/weather-app-react/",
  "name": "weather-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "@testing-library/user-event": "^13.1.9",
    "gh-pages": "^3.2.3",
    "node-sass": "^6.0.1",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "3.3.0",
    "styled-components": "^5.3.0",
    "yarn": "^1.22.10"
  },
  "scripts": {
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^6.0.0",
    "lint-staged": "^11.0.0",
    "prettier": "2.3.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "prettier -config .prettier --write",
      "eslint --fix",
      "git add"
    ]
  }
}

```
Now just del package-lock.json, and node-modules folder.... After thatrun npm install ;) Hope it works! And even del .eslint and .prettier file....

**Comment by ItsLeon15** [comment]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:424:7)
    at noopServiceWorkerMiddleware (C:\Users\Build 45\Downloads\1\1\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\Users\Build 45\Downloads\1\1\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\Users\Build 45\Downloads\1\1\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\Users\Build 45\Downloads\1\1\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by Jaideep25** [comment]
What's your react scripts version? If you're on discord please do add me : Jaideep25#2525, instead of creatin a mess here .-.
